services:
  postgres:
    container_name: stock-manager-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: stock-manager
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres