import { UnitMeasure } from "@generated/prisma/client";

export interface GroupTemplate {
  code: string;
  name: string;
  description: string;
}

export interface MaterialTemplate {
  name: string;
  unit: UnitMeasure;
  description?: string;
}

export const GROUP_TEMPLATES: GroupTemplate[] = [
  {
    code: "PAR",
    name: "Parafusos",
    description: "Parafusos diversos, rosqueados, sextavados, etc.",
  },
  {
    code: "LIX",
    name: "Lixas",
    description: "Lixas abrasivas de diferentes granulações e formatos",
  },
  {
    code: "CAB",
    name: "Cabos e Fios",
    description: "Cabos elétricos, fios, conectores e acessórios",
  },
  {
    code: "TIN",
    name: "Tintas e Vernizes",
    description: "Tintas, vernizes, primers e produtos para acabamento",
  },
  {
    code: "VED",
    name: "Vedantes e Selantes",
    description: "Silicones, borrachas, veda-roscas e materiais de vedação",
  },
  {
    code: "ARR",
    name: "Anilhas e Arruelas",
    description: "Anilhas, arruelas planas, de pressão e outros retentores",
  },
  {
    code: "POR",
    name: "Porcas e Parafusos",
    description: "Porcas, parafusos auto-atarraxantes, buchas e fixadores",
  },
  {
    code: "PRE",
    name: "Pregos e Rebites",
    description: "Pregos de diferentes tamanhos, rebites e grampos",
  },
  {
    code: "ADE",
    name: "Adesivos e Colas",
    description: "Colas, adesivos, fitas adesivas e produtos de fixação",
  },
];

export const MATERIALS_BY_GROUP: Record<string, MaterialTemplate[]> = {
  Parafusos: [
    { name: "Parafuso Sextavado M6x20", unit: UnitMeasure.UN },
    { name: "Parafuso Sextavado M8x25", unit: UnitMeasure.UN },
    { name: "Parafuso Sextavado M10x30", unit: UnitMeasure.UN },
    { name: "Parafuso Sextavado M12x40", unit: UnitMeasure.UN },
    { name: "Parafuso Sextavado M16x50", unit: UnitMeasure.UN },
    { name: "Parafuso Sextavado M20x60", unit: UnitMeasure.UN },
    { name: "Parafuso Phillips #8x20", unit: UnitMeasure.UN },
    { name: "Parafuso Phillips #10x25", unit: UnitMeasure.UN },
    { name: "Parafuso Phillips #12x30", unit: UnitMeasure.UN },
    { name: "Parafuso Allen M5x16", unit: UnitMeasure.UN },
    { name: "Parafuso Allen M6x20", unit: UnitMeasure.UN },
    { name: "Parafuso Allen M8x25", unit: UnitMeasure.UN },
    { name: "Parafuso Rosca Soberba 1/4x20", unit: UnitMeasure.UN },
    { name: "Parafuso Rosca Soberba 5/16x25", unit: UnitMeasure.UN },
    { name: "Parafuso Rosca Soberba 3/8x30", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 3.5x16", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 4.0x20", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 4.5x25", unit: UnitMeasure.UN },
    { name: "Parafuso Torx T20x30", unit: UnitMeasure.UN },
    { name: "Parafuso Torx T25x40", unit: UnitMeasure.UN },
    { name: "Parafuso Para Madeira 4x40", unit: UnitMeasure.UN },
    { name: "Parafuso Para Madeira 5x50", unit: UnitMeasure.UN },
    { name: "Parafuso Para Madeira 6x60", unit: UnitMeasure.UN },
    { name: "Parafuso Inox M6x20", unit: UnitMeasure.UN },
    { name: "Parafuso Inox M8x25", unit: UnitMeasure.UN },
    { name: "Parafuso Latão M6x20", unit: UnitMeasure.UN },
    { name: "Parafuso Latão M8x25", unit: UnitMeasure.UN },
    { name: "Parafuso Tirafundo 6x60", unit: UnitMeasure.UN },
    { name: "Parafuso Tirafundo 8x80", unit: UnitMeasure.UN },
    { name: "Parafuso Tirafundo 10x100", unit: UnitMeasure.UN },
  ],
  Lixas: [
    { name: "Lixa D'água #60", unit: UnitMeasure.UN },
    { name: "Lixa D'água #80", unit: UnitMeasure.UN },
    { name: "Lixa D'água #100", unit: UnitMeasure.UN },
    { name: "Lixa D'água #120", unit: UnitMeasure.UN },
    { name: "Lixa D'água #150", unit: UnitMeasure.UN },
    { name: "Lixa D'água #180", unit: UnitMeasure.UN },
    { name: "Lixa D'água #220", unit: UnitMeasure.UN },
    { name: "Lixa D'água #240", unit: UnitMeasure.UN },
    { name: "Lixa D'água #320", unit: UnitMeasure.UN },
    { name: "Lixa D'água #400", unit: UnitMeasure.UN },
    { name: "Lixa Corrente #60", unit: UnitMeasure.UN },
    { name: "Lixa Corrente #80", unit: UnitMeasure.UN },
    { name: "Lixa Corrente #100", unit: UnitMeasure.UN },
    { name: "Lixa Corrente #120", unit: UnitMeasure.UN },
    { name: "Lixa Corrente #150", unit: UnitMeasure.UN },
    { name: "Lixa Para Metal #80", unit: UnitMeasure.UN },
    { name: "Lixa Para Metal #100", unit: UnitMeasure.UN },
    { name: "Lixa Para Metal #120", unit: UnitMeasure.UN },
    { name: "Lixa Para Metal #150", unit: UnitMeasure.UN },
    { name: "Lixa Para Metal #180", unit: UnitMeasure.UN },
    { name: "Lixa Para Pintura #400", unit: UnitMeasure.UN },
    { name: "Lixa Para Pintura #600", unit: UnitMeasure.UN },
    { name: "Lixa Para Pintura #800", unit: UnitMeasure.UN },
    { name: "Lixa Para Pintura #1000", unit: UnitMeasure.UN },
    { name: "Lixa Para Pintura #1200", unit: UnitMeasure.UN },
    { name: "Lixa Para Vidro #600", unit: UnitMeasure.UN },
    { name: "Lixa Para Vidro #800", unit: UnitMeasure.UN },
    { name: "Lixa Para Vidro #1000", unit: UnitMeasure.UN },
    { name: "Lixa Abrasiva 3M #80", unit: UnitMeasure.SC },
    { name: "Lixa Abrasiva 3M #120", unit: UnitMeasure.SC },
  ],
  "Cabos e Fios": [
    { name: "Cabo Flexível 1.5mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 2.5mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 4.0mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 6.0mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 10mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 16mm²", unit: UnitMeasure.M },
    { name: "Cabo Flexível 25mm²", unit: UnitMeasure.M },
    { name: "Cabo Rígido 1.5mm²", unit: UnitMeasure.M },
    { name: "Cabo Rígido 2.5mm²", unit: UnitMeasure.M },
    { name: "Cabo Rígido 4.0mm²", unit: UnitMeasure.M },
    { name: "Cabo Rígido 6.0mm²", unit: UnitMeasure.M },
    { name: "Cabo Rígido 10mm²", unit: UnitMeasure.M },
    { name: "Fio Esmaltado 0.5mm", unit: UnitMeasure.M },
    { name: "Fio Esmaltado 0.8mm", unit: UnitMeasure.M },
    { name: "Fio Esmaltado 1.0mm", unit: UnitMeasure.M },
    { name: "Fio Esmaltado 1.5mm", unit: UnitMeasure.M },
    { name: "Cabo Coaxial RG6", unit: UnitMeasure.M },
    { name: "Cabo Coaxial RG59", unit: UnitMeasure.M },
    { name: "Cabo de Rede CAT5E", unit: UnitMeasure.M },
    { name: "Cabo de Rede CAT6", unit: UnitMeasure.M },
    { name: "Cabo de Rede CAT6A", unit: UnitMeasure.M },
    { name: "Conector RJ45", unit: UnitMeasure.UN },
    { name: "Conector BNC", unit: UnitMeasure.UN },
    { name: "Conector Fêmea", unit: UnitMeasure.UN },
    { name: "Terminal Elétrico", unit: UnitMeasure.PC },
    { name: "Cabo Flexível Antichama", unit: UnitMeasure.M },
    { name: "Cabo Flexível Solar", unit: UnitMeasure.M },
    { name: "Fio Terra 16mm²", unit: UnitMeasure.M },
    { name: "Fio Terra 25mm²", unit: UnitMeasure.M },
    { name: "Cabo Multifilar 7x0.5", unit: UnitMeasure.M },
  ],
  "Tintas e Vernizes": [
    { name: "Tinta Acrílica Branca 18L", unit: UnitMeasure.GAL },
    { name: "Tinta Acrílica Branca 3.6L", unit: UnitMeasure.LT },
    { name: "Tinta Acrílica Branca 900ML", unit: UnitMeasure.L },
    { name: "Tinta Esmalte Sintético Branco", unit: UnitMeasure.GAL },
    { name: "Tinta Esmalte Sintético Preto", unit: UnitMeasure.GAL },
    { name: "Tinta Esmalte Sintético Vermelho", unit: UnitMeasure.GAL },
    { name: "Tinta Esmalte Sintético Azul", unit: UnitMeasure.GAL },
    { name: "Tinta Esmalte Sintético Amarelo", unit: UnitMeasure.GAL },
    { name: "Tinta Epóxi Branca", unit: UnitMeasure.KIT },
    { name: "Tinta Epóxi Preta", unit: UnitMeasure.KIT },
    { name: "Verniz Brilhante", unit: UnitMeasure.L },
    { name: "Verniz Fosco", unit: UnitMeasure.L },
    { name: "Verniz Marítimo", unit: UnitMeasure.L },
    { name: "Primer Antióxido", unit: UnitMeasure.L },
    { name: "Primer Acrílico", unit: UnitMeasure.L },
    { name: "Tinta Base Branca", unit: UnitMeasure.L },
    { name: "Tinta Base Amarela", unit: UnitMeasure.L },
    { name: "Tinta Base Vermelha", unit: UnitMeasure.L },
    { name: "Tinta Base Azul", unit: UnitMeasure.L },
    { name: "Tinta Base Preta", unit: UnitMeasure.L },
    { name: "Tinta Spray Preta", unit: UnitMeasure.UN },
    { name: "Tinta Spray Branca", unit: UnitMeasure.UN },
    { name: "Tinta Spray Prata", unit: UnitMeasure.UN },
    { name: "Tinta Spray Transparente", unit: UnitMeasure.UN },
    { name: "Solvente Para Tinta", unit: UnitMeasure.L },
    { name: "Diluidor Universal", unit: UnitMeasure.L },
    { name: "Tinta Para Piso", unit: UnitMeasure.GAL },
    { name: "Tinta Antichama", unit: UnitMeasure.GAL },
    { name: "Tinta Elástica", unit: UnitMeasure.GAL },
    { name: "Laca Automotiva Branca", unit: UnitMeasure.L },
  ],
  "Vedantes e Selantes": [
    { name: "Silicone Branco", unit: UnitMeasure.UN },
    { name: "Silicone Transparente", unit: UnitMeasure.UN },
    { name: "Silicone Preto", unit: UnitMeasure.UN },
    { name: "Silicone Acético", unit: UnitMeasure.UN },
    { name: "Silicone Neutro", unit: UnitMeasure.UN },
    { name: "Silicone Para Telhado", unit: UnitMeasure.UN },
    { name: "Silicone Para Vidro", unit: UnitMeasure.UN },
    { name: "Silicone Para Motor", unit: UnitMeasure.UN },
    { name: "Silicone High Temp", unit: UnitMeasure.UN },
    { name: "Silicone Sanitário", unit: UnitMeasure.UN },
    { name: "Veda-Rosca Branco", unit: UnitMeasure.RL },
    { name: "Veda-Rosca Amarelo", unit: UnitMeasure.RL },
    { name: "Veda-Rosca Azul", unit: UnitMeasure.RL },
    { name: "Fita Veda-Rosca PTFE", unit: UnitMeasure.RL },
    { name: "Junta de Vedação Para Motor", unit: UnitMeasure.UN },
    { name: "Junta de Vedação Para Cárter", unit: UnitMeasure.UN },
    { name: "Boracha de Vedação", unit: UnitMeasure.M },
    { name: "Gaxeta de Vedação", unit: UnitMeasure.UN },
    { name: "Selante Poliuretânico", unit: UnitMeasure.UN },
    { name: "Selante Acrílico", unit: UnitMeasure.UN },
    { name: "Massa Vedante", unit: UnitMeasure.KG },
    { name: "Pasta Selante", unit: UnitMeasure.KG },
    { name: "Vedação para Porta", unit: UnitMeasure.M },
    { name: "Vedação para Janela", unit: UnitMeasure.M },
    { name: "Espuma Expansiva", unit: UnitMeasure.UN },
    { name: "Espuma de Vedação", unit: UnitMeasure.M },
    { name: "Corda de Vedação", unit: UnitMeasure.M },
    { name: "Corda de Amianto", unit: UnitMeasure.KG },
    { name: "Fita Isolante PVC", unit: UnitMeasure.RL },
    { name: "Fita Isolante Preta", unit: UnitMeasure.RL },
  ],
  "Anilhas e Arruelas": [
    { name: "Arruela Lisa M6", unit: UnitMeasure.UN },
    { name: "Arruela Lisa M8", unit: UnitMeasure.UN },
    { name: "Arruela Lisa M10", unit: UnitMeasure.UN },
    { name: "Arruela Lisa M12", unit: UnitMeasure.UN },
    { name: "Arruela Lisa M16", unit: UnitMeasure.UN },
    { name: "Arruela Lisa M20", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M6", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M8", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M10", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M12", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M16", unit: UnitMeasure.UN },
    { name: "Arruela de Pressão M20", unit: UnitMeasure.UN },
    { name: "Arruela Grower M6", unit: UnitMeasure.UN },
    { name: "Arruela Grower M8", unit: UnitMeasure.UN },
    { name: "Arruela Grower M10", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Externa 20mm", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Externa 25mm", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Externa 30mm", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Interna 10mm", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Interna 12mm", unit: UnitMeasure.UN },
    { name: "Anilha Seeger Interna 15mm", unit: UnitMeasure.UN },
    { name: "Anilha Retentora", unit: UnitMeasure.UN },
    { name: "Anilha Elástica", unit: UnitMeasure.UN },
    { name: "Arruela Inox M6", unit: UnitMeasure.UN },
    { name: "Arruela Inox M8", unit: UnitMeasure.UN },
    { name: "Arruela Inox M10", unit: UnitMeasure.UN },
    { name: "Arruela Inox M12", unit: UnitMeasure.UN },
    { name: "Arruela Latão M6", unit: UnitMeasure.UN },
    { name: "Arruela Latão M8", unit: UnitMeasure.UN },
    { name: "Arruela Latão M10", unit: UnitMeasure.UN },
  ],
  "Porcas e Parafusos": [
    { name: "Porca Sextavada M6", unit: UnitMeasure.UN },
    { name: "Porca Sextavada M8", unit: UnitMeasure.UN },
    { name: "Porca Sextavada M10", unit: UnitMeasure.UN },
    { name: "Porca Sextavada M12", unit: UnitMeasure.UN },
    { name: "Porca Sextavada M16", unit: UnitMeasure.UN },
    { name: "Porca Sextavada M20", unit: UnitMeasure.UN },
    { name: "Porca Inox M6", unit: UnitMeasure.UN },
    { name: "Porca Inox M8", unit: UnitMeasure.UN },
    { name: "Porca Inox M10", unit: UnitMeasure.UN },
    { name: "Porca Inox M12", unit: UnitMeasure.UN },
    { name: "Porca Allen M6", unit: UnitMeasure.UN },
    { name: "Porca Allen M8", unit: UnitMeasure.UN },
    { name: "Porca Allen M10", unit: UnitMeasure.UN },
    { name: "Bucha Expansiva 6x30", unit: UnitMeasure.UN },
    { name: "Bucha Expansiva 8x40", unit: UnitMeasure.UN },
    { name: "Bucha Expansiva 10x50", unit: UnitMeasure.UN },
    { name: "Bucha Expansiva 12x60", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 3.5x16", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 4.0x20", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 4.5x25", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 5.0x30", unit: UnitMeasure.UN },
    { name: "Parafuso Auto-atarraxante 6.0x40", unit: UnitMeasure.UN },
    { name: "Rebite Pop 4.0x10", unit: UnitMeasure.UN },
    { name: "Rebite Pop 4.8x12", unit: UnitMeasure.UN },
    { name: "Rebite Pop 6.0x16", unit: UnitMeasure.UN },
    { name: "Parafuso Prisioneiro M6x20", unit: UnitMeasure.UN },
    { name: "Parafuso Prisioneiro M8x25", unit: UnitMeasure.UN },
    { name: "Parafuso Prisioneiro M10x30", unit: UnitMeasure.UN },
    { name: "Porca Trocável M6", unit: UnitMeasure.UN },
    { name: "Porca Trocável M8", unit: UnitMeasure.UN },
  ],
  "Pregos e Rebites": [
    { name: "Prego 18x27", unit: UnitMeasure.KG },
    { name: "Prego 18x30", unit: UnitMeasure.KG },
    { name: "Prego 19x32", unit: UnitMeasure.KG },
    { name: "Prego 19x36", unit: UnitMeasure.KG },
    { name: "Prego 20x40", unit: UnitMeasure.KG },
    { name: "Prego 21x45", unit: UnitMeasure.KG },
    { name: "Prego 22x48", unit: UnitMeasure.KG },
    { name: "Prego 23x50", unit: UnitMeasure.KG },
    { name: "Prego Para Telhado 18x30", unit: UnitMeasure.KG },
    { name: "Prego Para Telhado 19x36", unit: UnitMeasure.KG },
    { name: "Prego Galvanizado 18x27", unit: UnitMeasure.KG },
    { name: "Prego Galvanizado 18x30", unit: UnitMeasure.KG },
    { name: "Prego Inox 18x27", unit: UnitMeasure.KG },
    { name: "Prego Inox 18x30", unit: UnitMeasure.KG },
    { name: "Rebite Cego 3.0x6", unit: UnitMeasure.UN },
    { name: "Rebite Cego 3.2x8", unit: UnitMeasure.UN },
    { name: "Rebite Cego 4.0x10", unit: UnitMeasure.UN },
    { name: "Rebite Cego 4.8x12", unit: UnitMeasure.UN },
    { name: "Rebite Cego 6.0x16", unit: UnitMeasure.UN },
    { name: "Rebite Sólido 3.0x6", unit: UnitMeasure.UN },
    { name: "Rebite Sólido 3.2x8", unit: UnitMeasure.UN },
    { name: "Rebite Sólido 4.0x10", unit: UnitMeasure.UN },
    { name: "Rebite Sólido 4.8x12", unit: UnitMeasure.UN },
    { name: "Rebite Sólido 6.0x16", unit: UnitMeasure.UN },
    { name: "Grampo Tipo U 10mm", unit: UnitMeasure.UN },
    { name: "Grampo Tipo U 15mm", unit: UnitMeasure.UN },
    { name: "Grampo Tipo U 20mm", unit: UnitMeasure.UN },
    { name: "Espigueta", unit: UnitMeasure.KG },
    { name: "Tachinha", unit: UnitMeasure.PC },
    { name: "Prego Para Forro", unit: UnitMeasure.KG },
  ],
  "Adesivos e Colas": [
    { name: "Cola Branca PVA 500g", unit: UnitMeasure.KG },
    { name: "Cola Branca PVA 1kg", unit: UnitMeasure.KG },
    { name: "Cola Branca PVA 5kg", unit: UnitMeasure.KG },
    { name: "Cola Para Madeira", unit: UnitMeasure.KG },
    { name: "Cola Epóxi", unit: UnitMeasure.KIT },
    { name: "Cola Super Bonder", unit: UnitMeasure.UN },
    { name: "Cola Super Bonder Grande", unit: UnitMeasure.UN },
    { name: "Cola Contact", unit: UnitMeasure.KG },
    { name: "Cola Para Borracha", unit: UnitMeasure.KG },
    { name: "Cola Para Metal", unit: UnitMeasure.KG },
    { name: "Cola Quente Bastão", unit: UnitMeasure.PC },
    { name: "Cola Quente Bastão Grande", unit: UnitMeasure.PC },
    { name: "Fita Adesiva Transparente 50mm", unit: UnitMeasure.RL },
    { name: "Fita Adesiva Transparente 48mm", unit: UnitMeasure.RL },
    { name: "Fita Adesiva Dupla Face", unit: UnitMeasure.RL },
    { name: "Fita Crepe", unit: UnitMeasure.RL },
    { name: "Fita Isolante Preta", unit: UnitMeasure.RL },
    { name: "Fita Isolante Colorida", unit: UnitMeasure.RL },
    { name: "Fita Alumínio", unit: UnitMeasure.RL },
    { name: "Fita Térmica", unit: UnitMeasure.RL },
    { name: "Adesivo Spray", unit: UnitMeasure.UN },
    { name: "Adesivo em Lata", unit: UnitMeasure.KG },
    { name: "Cola Para Azulejo", unit: UnitMeasure.KG },
    { name: "Cola Para PVC", unit: UnitMeasure.KG },
    { name: "Cola Para Isopor", unit: UnitMeasure.KG },
    { name: "Cola Para Tecido", unit: UnitMeasure.KG },
    { name: "Cola Para Vidro", unit: UnitMeasure.KG },
    { name: "Cola Para Couro", unit: UnitMeasure.KG },
    { name: "Adesivo Estrutural", unit: UnitMeasure.KG },
    { name: "Cola Instantânea Gotas", unit: UnitMeasure.UN },
  ],
};
